# General
name: Xenim
tagline: Höre deine Lieblingspodcasts live!

# Jekyll
exclude: ['Rakefile']
markdown: redcarpet

# App Store
appstore_url: https://itunes.apple.com/app/id123456789
appstore: <a href="https://itunes.apple.com/app/id123456789" class="app-store" rel="external nofollow"><img src="/assets/app-store.svg" alt="Download on the App Store"></a>
appstore_white: <a href="https://itunes.apple.com/app/id123456789" class="app-store" rel="external nofollow"><img src="/assets/app-store-white.svg" alt="Download on the App Store"></a>

# Screenshots
screenshots:
- screenshot01
- screenshot02
- screenshot03
- screenshot04
- screenshot05

# Company Info
company: Stefan Trauth
company_website: http://stefantrauth.de

# Emails
email_press: xenimapp@stefantrauth.de
email_contact: xenimapp@stefantrauth.de
email_support: xenimapp@stefantrauth.de
