# General
name: Xenim
tagline: Höre deine Lieblingspodcasts live!

# Jekyll
exclude: ['Rakefile']
markdown: redcarpet

# App Store
appstore_url: https://itunes.apple.com/app/id1073103750
appstore: <a href="https://itunes.apple.com/app/id1073103750" class="app-store" rel="external nofollow"><img src="/assets/app-store.svg" alt="Download on the App Store"></a>
appstore_white: <a href="https://itunes.apple.com/app/id1073103750" class="app-store" rel="external nofollow"><img src="/assets/app-store-white.svg" alt="Download on the App Store"></a>

# Screenshots
screenshots:
- iPhone5s-01Events
- iPhone5s-02PodcastDetail
- iPhone5s-03Player
- iPhone5s-04Favorites
- iPhone5s-05AddFavorites
- iPhone5s-06Settings

# Company Info
company: Stefan Trauth
company_website: http://stefantrauth.de

# Emails
email_press: xenimapp@stefantrauth.de
email_contact: xenimapp@stefantrauth.de
email_support: xenimapp@stefantrauth.de
